Repository codesquad-members-2023/be-java-was, pull requests merged in 2023-04, with the labels that each got.

#1 [이린] 주간 학습계획 초안 작성
  README.md
Labels: study plan

#2 [Hyun] 4월 첫째 주 학습 계획서 작성
  README.md
Labels: study plan

#3 [poro] 1주차 학습 계획 작성
  README.md
Labels: study plan

#4 [Birdie] 학습계획 작성
  README.md
Labels: study plan

#6 [core] - 1주차 학습 계획서 작성
  README.md
Labels: study plan

#8 [감자] 학습 계획 작성합니다.
  README.md
Labels: study plan

#10 [Dewey] 웹서버1 학습계획 제출
  README.md
Labels: study plan

#12 [ManJu] 학습 계획 작성 : 1주차
  README.md
Labels: step-1

#5 [니노] 학습계획서 작성 및 step-1 구현
  README.md
  src/main/java/util/HttpRequestUtils.java
  src/main/java/webserver/RequestHandler.java
Labels: study plan, step-1

#17 [cire] 학습계획서 작성
  README.md
  src/main/java/model/Head.java
  src/main/java/process/RequestProcess.java
  src/main/java/webserver/RequestHandler.java
  src/test/java/model/HeadTest.java
  src/test/java/process/RequestProcessTest.java
Labels: study plan

#11 [GOMUNGNAM] 주간 학습 계획 및 step-1 구현
  README.md
  src/main/java/utility/HttpRequestUtility.java
  src/main/java/webserver/RequestHandler.java
Labels: study plan, step-1

#13 [Hyun] step-1 : HTTP Request start-line 의 요청 URL 읽고 뷰 반환하기
  src/main/java/webserver/RequestHandler.java
Labels: step-1

#14 [Luke] 5주차 학습 계획, Step1 - 구현
  README.md
  src/main/java/webserver/RequestHandler.java
Labels: study plan, step-1

#18 [감자] stsep-1 학습, 구현
  README.md
  src/main/java/parser/HTTPRequestParser.java
  src/main/java/webserver/RequestHandler.java
  src/test/java/webserver/RequestHandlerTest.java
Labels: step-1

#19 [ManJu] Step01 : index.html 응답 & 모든 Request Header 출력
  src/main/java/db/Database.java
  src/main/java/util/HttpRequestUtils.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
Labels: step-1

#23 [이린] Step1 : index.html 응답
  build.gradle
  src/main/java/util/RequestParser.java
  src/main/java/webserver/RequestHandler.java
  src/test/java/util/RequestParserTest.java
Labels: step-1

#26 [core] (step-1) 정적 index.html 응답 기능 구현
  README.md
  src/main/java/util/HttpRequestUtils.java
  src/main/java/webserver/RequestHandler.java
  src/test/java/util/HttpRequestUtilsTest.java
Labels: step-1

#27 [로이] step-1 구현
  src/main/java/model/RequestHeader.java
  src/main/java/model/RequestLine.java
  src/main/java/webserver/GetURLCollection.java
  src/main/java/webserver/RequestHandler.java
Labels: step-1

#24 [poro] step2 - 회원가입, 회원가입 후 리다이렉트, 단위 테스트 구현
  src/main/java/controller/UserController.java
  src/main/java/util/HttpRequest.java
  src/main/java/util/HttpRequestUtils.java
  src/main/java/webserver/RequestHandler.java
Labels: step-2

#29 [Birdie] Step2 - GET 으로 회원가입
  README.md
  src/main/java/config/AppConfig.java
  src/main/java/controller/UserController.java
  src/main/java/service/UserJoinService.java
  src/main/java/webserver/RequestHandler.java
  src/test/java/service/UserJoinTest.java
Labels: step-2

#30 [nino] (step-2) GET으로 회원가입
  src/main/java/util/HttpRequestUtils.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
  src/test/java/util/HttpRequestUtilsTest.java
Labels: step-2

#31 [Luke] Step-2 구현
  src/main/java/controller/UserController.java
  src/main/java/util/RequestParser.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
  src/test/java/util/RequestParserTest.java
Labels: step-2

#33 [cire] Step-1 구현
  .gitignore
  src/main/java/model/Head.java
  src/main/java/process/RequestProcess.java
  src/main/java/webserver/RequestHandler.java
  src/test/java/model/HeadTest.java
  src/test/java/process/RequestProcessTest.java
Labels: step-1

#34 [Dewey] step-2 : get으로 회원가입하기 구현 (테스트코드x)
  src/main/java/db/Database.java
  src/main/java/user/User.java
  src/main/java/user/UserController.java
  src/main/java/util/HttpParser.java
  src/main/java/webserver/Request.java
  src/main/java/webserver/RequestController.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/RequestLine.java
  src/main/java/webserver/Response.java
  src/main/java/webserver/WebServer.java
  src/main/resources/templates/index.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
Labels: step-2

#35 [Hyun] step-3 : StyleSheet 지원
  src/main/java/model/StartLine.java
  src/main/java/webserver/HttpRequest.java
  src/main/java/webserver/HttpRequestMessageParser.java
  src/main/java/webserver/HttpResponse.java
  src/main/java/webserver/RequestHandler.java
  src/test/java/model/StartLineTest.java
  src/test/java/webserver/HttpRequestMessageParserTest.java
  src/test/java/webserver/HttpRequestTest.java
  src/test/java/webserver/HttpResponseTest.java
Labels: step-3

#36 [poro] step-3 Stylesheet 지원 및 클라이언트 소켓 구현
  build.gradle
  src/main/java/controller/UserController.java
  src/main/java/request/HttpRequest.java
  src/main/java/request/HttpRequestUtils.java
  src/main/java/response/ContentsType.java
  src/main/java/response/HttpHeaders.java
  src/main/java/response/HttpResponse.java
  src/main/java/util/HttpRequest.java
  src/main/java/util/SocketStatusChecker.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
  src/test/java/client/WebClient.java
  src/test/java/controller/UserControllerTest.java
  src/test/java/util/HttpRequestTest.java
  src/test/java/util/HttpRequestUtilsTest.java
Labels: step-3

#37 [ManJu] Step02 : GET 으로 회원가입(테스트 X)
  src/main/java/util/HttpRequestUtils.java
  src/main/java/util/Pair.java
  src/main/java/util/ParseQueryUtils.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
Labels: step-2

#39 [감자] step-2 구현
  README.md
  img.png
  src/main/java/model/User.java
  src/main/java/parser/HTTPRequestParser.java
  src/main/java/request/HttpRequest.java
  src/main/java/response/HttpResponse.java
  src/main/java/util/HttpRequestUtils.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/RequestMapping.java
Labels: step-2

#40 [Birdie] Step-3
  src/main/java/config/AppConfig.java
  src/main/java/controller/UserController.java
  src/main/java/service/UserJoinService.java
  src/main/java/util/ContentType.java
  src/main/java/util/HttpRequest.java
  src/main/java/util/HttpResponse.java
  src/main/java/util/HttpStatus.java
  src/main/java/util/ResponseBody.java
  src/main/java/webserver/RequestHandler.java
  src/main/resources/templates/user/form.html
  src/test/java/util/HttpRequestUtilTest.java
Labels: step-3

#42 [ManJu] Step02 : 테스트 추가 & 요구사항 반영
  src/main/java/util/HttpRequestUtils.java
  src/main/java/util/ParseQueryUtils.java
  src/main/java/webserver/RequestHandler.java
  src/test/java/util/ParseQueryUtilsTest.java
Labels: step-2

#41 [이린](step-3) stylesheet 지원 / 설계 변경
  README.md
  src/main/java/config/AppConfig.java
  src/main/java/controller/Controller.java
  src/main/java/controller/FrontController.java
  src/main/java/controller/UserController.java
  src/main/java/controller/ViewController.java
  src/main/java/model/User.java
  src/main/java/service/UserService.java
  src/main/java/util/ProtocolParser.java
  src/main/java/util/RequestParser.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
  src/main/java/webserver/protocol/ContentType.java
  src/main/java/webserver/protocol/HttpRequest.java
  src/main/java/webserver/protocol/HttpResponse.java
  src/main/java/webserver/protocol/Method.java
  src/test/java/service/MemberServiceTest.java
  src/test/java/util/ProtocolParserTest.java
  src/test/java/util/RequestParserTest.java
Labels: step-3

#44 [Hyun] step-3 피드백을 반영한 리팩토링 : 네이밍, HTTP Response 테스트 코드 추가, *.ico *.png 타입 추가
  src/main/java/model/RequestType.java
  src/main/java/model/StartLine.java
  src/main/java/webserver/HttpRequest.java
  src/main/java/webserver/HttpResponse.java
  src/main/resources/static/favicon.ico
  src/test/java/model/StartLineTest.java
  src/test/java/webserver/HttpRequestTest.java
  src/test/java/webserver/HttpResponseTest.java
Labels: enhancement

#46 [Luke] Step2 - 리팩토링
  src/main/java/controller/UserController.java
  src/main/java/db/Database.java
  src/main/java/model/User.java
  src/main/java/util/SingletonContainer.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
  src/test/java/util/RequestParserTest.java
  src/test/java/util/SingletonContainerTest.java
Labels: enhancement, step-2

#47 [ManJu] Step03 : 컨텐츠 타입 지원 기능 구현
  src/main/java/util/HttpRequestUtils.java
  src/main/java/util/HttpResponseUtils.java
  src/main/java/util/stylesheetUtils.java
  src/main/java/webserver/RequestHandler.java
  src/main/resources/logback.xml
  src/main/resources/static/css/styles.css
  src/main/resources/static/fonts/glyphicons-halflings-regular.svg
  src/main/resources/static/js/scripts.js
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/test/java/util/ParseQueryUtilsTest.java
Labels: step-3

#48 [nino] step-3 구현
  src/main/java/util/ContentType.java
  src/main/java/util/HttpRequestUtils.java
  src/main/java/webserver/HttpRequest.java
  src/main/java/webserver/HttpResponse.java
  src/main/java/webserver/RequestHandler.java
  src/test/java/util/ContentTypeTest.java
  src/test/java/util/HttpRequestTest.java
Labels: step-3

#50 [poro] step3 피드백 반영 및 리팩터링 : ContentType 개선, UrlMapper, View, ViewResolver
  src/main/java/controller/UrlMapper.java
  src/main/java/controller/UserController.java
  src/main/java/response/ContentsType.java
  src/main/java/response/HttpHeaders.java
  src/main/java/response/HttpResponse.java
  src/main/java/response/Status.java
  src/main/java/view/View.java
  src/main/java/view/ViewResolver.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
Labels: enhancement, step-3

#51 [감자] step3 구현
  README.md
  src/main/java/controller/Controller.java
  src/main/java/controller/DefaultController.java
  src/main/java/controller/FrontController.java
  src/main/java/controller/HomeController.java
  src/main/java/controller/ResourceController.java
  src/main/java/controller/UserController.java
  src/main/java/request/ContentType.java
  src/main/java/request/HttpRequest.java
  src/main/java/response/HttpResponse.java
  src/main/java/response/HttpStatus.java
  src/main/java/util/HttpMethod.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/RequestMapping.java
  src/main/resources/templates/user/form.html
Labels: step-3

#52 [GOMUNGNAM] (step-2) GET으로 회원가입
  src/main/java/controller/UserController.java
  src/main/java/utility/HttpRequestUtility.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
Labels: step-2

#54 [로이] step-2 (회원가입, 리다이렉트) 구현
  src/main/java/db/Database.java
  src/main/java/model/InputRequestParser.java
  src/main/java/model/RequestLine.java
  src/main/java/model/Response.java
  src/main/java/model/UrlMethodMappingGenerator.java
  src/main/java/webserver/GetMappingProvider.java
  src/main/java/webserver/GetURLCollection.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
  src/main/resources/logback.xml
  src/main/resources/static/css/styles.css
  src/main/resources/static/fonts/glyphicons-halflings-regular.svg
  src/main/resources/static/js/scripts.js
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
Labels: step-2

#38 [cire] Step-2 GET 요청으로 회원가입 기능 구현
  src/main/java/controller/UserController.java
  src/main/java/model/Head.java
  src/main/java/model/HttpRequest.java
  src/main/java/model/HttpResponse.java
  src/main/java/process/RequestProcess.java
  src/main/java/service/UserService.java
  src/main/java/util/HttpMethod.java
  src/main/java/util/MyObjectMapper.java
  src/main/java/webserver/HttpServlet.java
  src/main/java/webserver/RequestHandler.java
  src/test/java/model/HeadTest.java
  src/test/java/process/RequestProcessTest.java
  src/test/java/service/UserServiceTest.java
Labels: step-2

#45 [이린](refactor) 시그니처 수정 / `Response Statecode` enum 정의 /
  src/main/java/controller/UserController.java
  src/main/java/controller/ViewController.java
  src/main/java/util/ProtocolParser.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/protocol/ContentType.java
  src/main/java/webserver/protocol/HttpRequest.java
  src/main/java/webserver/protocol/HttpResponse.java
  src/main/java/webserver/protocol/StatusCode.java
  src/test/java/util/ProtocolParserTest.java
Labels: step-3

#55 [로이] step-3 (컨텐트 타입 지원) 구현
  src/main/java/model/Response.java
  src/main/java/webserver/GetMappingProvider.java
Labels: step-3

#56 [Hyun] 4월 둘째 주 학습 계획서 작성
  README.md
Labels: study plan

#57 [Luke] - 6주차 학습 계획, step-3 구현
  README.md
  src/main/java/util/ContentTypeMapper.java
  src/main/java/webserver/HttpRequestHeader.java
  src/main/java/webserver/HttpResponseBuilder.java
  src/main/java/webserver/RequestHandler.java
Labels: study plan, step-3

#59 [nino] 학습계획서 작성
  README.md
  src/main/java/webserver/WebServer.java
Labels: study plan

#62 [이린](docs) : 2주차 학습 계획 작성
  README.md
Labels: study plan

#61 [cire]학습 계획서 작성
  README.md
Labels: study plan

#58 [ManJu] Step03 : 테스트 추가 & 요구사항 반영(enum 사용) & 학습계획 작성
  README.md
  src/main/java/util/ContentType.java
  src/main/java/util/HttpRequestUtils.java
  src/main/java/util/stylesheetUtils.java
  src/main/java/webserver/RequestHandler.java
  src/test/java/util/HttpRequestUtilsTest.java
  src/test/java/util/ParseQueryUtilsTest.java
  src/test/java/util/StylesheetUtilsTest.java
Labels: study plan, step-3

#64 [cire] Step-4 : Post로 회원 가입 기능 구현
  src/main/java/configure/ResolverConfigure.java
  src/main/java/controller/UserController.java
  src/main/java/model/HttpRequest.java
  src/main/java/model/HttpResponse.java
  src/main/java/service/UserService.java
  src/main/java/util/HttpMethod.java
  src/main/java/util/HttpResponseResolver.java
  src/main/java/util/MyObjectMapper.java
  src/main/java/util/MyObjectMapperByMap.java
  src/main/java/util/MyObjectMapperByString.java
  src/main/java/webserver/HttpServlet.java
  src/main/java/webserver/RequestHandler.java
  src/test/java/model/HeadTest.java
  src/test/java/util/MyObjectMapperByMapTest.java
  src/test/java/util/MyObjectMapperByStringTest.java
  src/test/java/util/MyObjectMapperTest.java
Labels: step-4

#65 [Birdie] Step - 4 POST 로 회원가입
  src/main/java/config/AppConfig.java
  src/main/java/controller/URLController.java
  src/main/java/controller/UserController.java
  src/main/java/request/HttpRequest.java
  src/main/java/response/HttpResponse.java
  src/main/java/service/ConstructorMapper.java
  src/main/java/service/UserJoinService.java
  src/main/java/util/ContentType.java
  src/main/java/util/HttpRequest.java
  src/main/java/util/HttpStatus.java
  src/main/java/util/IOUtils.java
  src/main/java/util/ResponseBody.java
  src/main/java/webserver/RequestHandler.java
  src/main/resources/templates/index.html
  src/main/resources/templates/user/form.html
  src/test/java/util/HttpRequestUtilTest.java
Labels: step-4

#66 [poro] Step-4 POST로 회원가입
  src/main/java/controller/UrlMapper.java
  src/main/java/controller/UserController.java
  src/main/java/request/HttpRequest.java
  src/main/java/response/ContentsType.java
  src/main/java/response/HttpHeaders.java
  src/main/java/response/HttpResponse.java
  src/main/java/view/View.java
  src/main/java/view/ViewResolver.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
  src/main/resources/templates/user/form.html
Labels: step-4

#68 [Dewey] step-3 구현 : accept 활용해서 content-Type 설정 구현
  README.md
  src/main/java/user/UserController.java
  src/main/java/webserver/Request.java
  src/main/java/webserver/RequestController.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/RequestLine.java
  src/main/java/webserver/Response.java
  src/main/java/webserver/StatusCode.java
  src/main/resources/static/favicon.ico
  src/test/java/util/HttpParserTest.java
Labels: step-3

#63 [이린] (step-4) : post로 회원가입
  README.md
  build.gradle
  src/main/java/config/AppConfig.java
  src/main/java/controller/Controller.java
  src/main/java/controller/DefaultController.java
  src/main/java/controller/FrontController.java
  src/main/java/controller/HandlerMapping.java
  src/main/java/controller/UserController.java
  src/main/java/controller/ViewController.java
  src/main/java/util/ProtocolParser.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/protocol/HttpRequest.java
  src/main/java/webserver/protocol/HttpResponse.java
  src/main/java/webserver/protocol/Method.java
  src/main/resources/templates/index.html
  src/main/resources/templates/user/form.html
  src/test/java/controller/HandlerMappingTest.java
  src/test/java/controller/UserControllerTest.java
  src/test/java/util/ProtocolParserTest.java
Labels: step-4

#69 [감자] Step-4 post기능 구현, 리팩토링 제출합니다
  src/main/java/Controller.java
  src/main/java/RequestMapping.java
  src/main/java/controller/DefaultController.java
  src/main/java/controller/FrontController.java
  src/main/java/controller/HomeController.java
  src/main/java/controller/ResourceController.java
  src/main/java/controller/UserController.java
  src/main/java/request/ContentType.java
  src/main/java/request/HttpRequest.java
  src/main/java/request/HttpRequestBody.java
  src/main/java/request/HttpRequestHeader.java
  src/main/java/request/HttpRequestStartLine.java
  src/main/java/response/HttpResponse.java
  src/main/java/response/HttpStatus.java
  src/main/java/util/HttpMethod.java
  src/main/java/view/MyView.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/RequestMapping.java
Labels: step-4

#72 [Luke] step3 / 구조 리팩토링
  src/main/java/controller/UserController.java
  src/main/java/webserver/ContentTypeParser.java
  src/main/java/webserver/HttpRequest.java
  src/main/java/webserver/HttpResponseBuilderV1.java
  src/main/java/webserver/NotFoundResponseBuilder.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/RightResponseBuilder.java
  src/main/resources/templates/util/error.html
Labels: enhancement, step-3

#70 [poro] step 4 컨트롤러 리팩터링, Annotation 자동 URL 매핑 구현
  build.gradle
  src/main/java/annotation/MethodType.java
  src/main/java/annotation/RequestMapping.java
  src/main/java/controller/Controller.java
  src/main/java/controller/FrontController.java
  src/main/java/controller/HandlerMapper.java
  src/main/java/controller/HomeController.java
  src/main/java/controller/UrlMapper.java
  src/main/java/controller/UserJoinController.java
  src/main/java/controller/UserLoginController.java
  src/main/java/db/Database.java
  src/main/java/response/HttpHeaders.java
  src/main/java/response/HttpResponse.java
  src/main/java/view/ViewResolver.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
  src/main/resources/templates/user/login.html
  src/test/java/controller/FrontControllerTest.java
  src/test/java/controller/UserControllerTest.java
  src/test/java/util/HttpRequestTest.java
Labels: enhancement, step-4

#73 [GOMUNGNAM](step-3) 컨텐츠 타입 지원 - Accept로 처리하기
  src/main/java/config/AppConfig.java
  src/main/java/controller/UserController.java
  src/main/java/request/Request.java
  src/main/java/request/RequestParser.java
  src/main/java/response/Response.java
  src/main/java/service/UserSignUpService.java
  src/main/java/utility/HttpRequestUtility.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
Labels: step-3

#75 [Hyun] step-4 구현 : POST 요청으로 User 생성, redirect 구현
  src/main/java/model/RequestLine.java
  src/main/java/model/RequestType.java
  src/main/java/model/StartLine.java
  src/main/java/servlet/DispatcherServlet.java
  src/main/java/servlet/controller/Controller.java
  src/main/java/servlet/controller/IndexController.java
  src/main/java/servlet/controller/UserFormController.java
  src/main/java/servlet/controller/UserSaveController.java
  src/main/java/util/RequestSeparater.java
  src/main/java/webserver/HttpRequest.java
  src/main/java/webserver/HttpResponse.java
  src/main/java/webserver/RequestHandler.java
  src/main/resources/templates/user/form.html
  src/test/java/model/RequestLineTest.java
  src/test/java/model/StartLineTest.java
  src/test/java/servlet/controller/IndexControllerTest.java
  src/test/java/servlet/controller/UserFormControllerTest.java
  src/test/java/servlet/controller/UserSaveControllerTest.java
  src/test/java/util/RequestSeparaterTest.java
  src/test/java/webserver/HttpRequestTest.java
  src/test/java/webserver/HttpResponseTest.java
Labels: step-4

#67 [ManJu] Step04 : POST 가입 방식 구현 & 302code + redirect 구현
  src/main/java/db/Database.java
  src/main/java/model/ContentType.java
  src/main/java/model/Pair.java
  src/main/java/model/RequestInfo.java
  src/main/java/model/Stylesheet.java
  src/main/java/model/User.java
  src/main/java/util/ContentType.java
  src/main/java/util/HttpRequestUtils.java
  src/main/java/util/ParseQueryUtils.java
  src/main/java/util/stylesheetUtils.java
  src/main/java/webserver/GETHandler.java
  src/main/java/webserver/POSTHandler.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/ResponseHandler.java
  src/main/resources/templates/user/form.html
  src/test/java/util/HttpRequestUtilsTest.java
  src/test/java/util/ParseQueryUtilsTest.java
  src/test/java/webserver/GETHandlerTest.java
  src/test/java/webserver/POSTHandlerTest.java
Labels: step-4

#78 [니노] step-4 post로 구현
  src/main/java/Controller/UserController.java
  src/main/java/request/HttpRequest.java
  src/main/java/response/HttpResponse.java
  src/main/java/util/ContentType.java
  src/main/java/util/MethodStatus.java
  src/main/java/util/ResponseStatus.java
  src/main/java/webserver/HttpRequest.java
  src/main/java/webserver/RequestHandler.java
  src/main/resources/templates/user/form.html
  src/test/java/util/ContentTypeTest.java
  src/test/java/util/HttpRequestTest.java
  src/test/java/webserver/HttpRequestTest.java
Labels: step-4

#81 [nino] step-4 리팩토링
  src/main/java/Controller/UserController.java
  src/main/java/request/HttpRequest.java
  src/main/java/webserver/RequestHandler.java
  src/test/java/webserver/HttpRequestTest.java
Labels: step-4

#82 [dewey] step-4 : 3단계 피드백 반영, post로 회원가입 구현,
  README.md
  src/main/java/user/UserController.java
  src/main/java/webserver/ContentType.java
  src/main/java/webserver/Request.java
  src/main/java/webserver/RequestController.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/Response.java
  src/main/java/webserver/StatusCode.java
  src/main/resources/templates/user/form.html
Labels: step-4

#84 [Hyun] 4월 셋째 주 학습계획
  README.md
Labels: study plan

#85 [cire] 학습 계획서 작성
  README.md
Labels: study plan

#86 [니노] 학습계획서 제출
  README.md
Labels: study plan

#87 [Hyun] step-6 구현 : 로그인 여부에 따른 접근 설정 및 동적 HTML 생성
  src/main/java/db/Database.java
  src/main/java/servlet/DispatcherServlet.java
  src/main/java/servlet/controller/UserListController.java
  src/main/java/servlet/controller/UserSaveController.java
  src/main/java/util/StatusCode.java
  src/main/java/util/UserSession.java
  src/main/java/webserver/HttpResponse.java
  src/main/java/webserver/RequestHandler.java
  src/main/resources/templates/index.html
  src/main/resources/templates/user/list.html
  src/test/java/servlet/controller/IndexControllerTest.java
  src/test/java/servlet/controller/UserListControllerTest.java
  src/test/java/servlet/controller/UserSaveControllerTest.java
  src/test/java/util/UserSessionTest.java
  src/test/java/webserver/HttpResponseTest.java
Labels: step-6

#88 [Luke] (step-4) POST로 회원가입 구현
  src/main/java/controller/UserController.java
  src/main/java/db/Database.java
  src/main/java/request/HttpRequest.java
  src/main/java/request/HttpRequestBody.java
  src/main/java/request/HttpRequestHeader.java
  src/main/java/request/HttpRequestLine.java
  src/main/java/response/HttpResponseBuilder.java
  src/main/java/response/NotFoundResponseBuilder.java
  src/main/java/response/RedirectResponseBuilder.java
  src/main/java/response/RightResponseBuilder.java
  src/main/java/webserver/ContentTypeParser.java
  src/main/java/webserver/HttpRequest.java
  src/main/java/webserver/HttpResponseBuilderV1.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
  src/main/resources/templates/error.html
  src/main/resources/templates/user/form.html
Labels: enhancement, step-4

#89 [poro] step6 - 동적인 HTML, 템플릿 엔진 프로토타입 구현
  README.md
  img.png
  src/main/java/controller/Controller.java
  src/main/java/controller/HomeController.java
  src/main/java/controller/UserJoinController.java
  src/main/java/controller/UserListController.java
  src/main/java/controller/UserLoginController.java
  src/main/java/db/Database.java
  src/main/java/mapper/ExceptionMapper.java
  src/main/java/request/HttpRequest.java
  src/main/java/request/HttpRequestUtils.java
  src/main/java/response/HttpHeaders.java
  src/main/java/response/HttpResponse.java
  src/main/java/session/Session.java
  src/main/java/session/SessionDb.java
  src/main/java/session/SessionGenerator.java
  src/main/java/templateEngine/PoroTouch.java
  src/main/java/util/SocketStatusChecker.java
  src/main/java/view/ModelAndView.java
  src/main/java/view/View.java
  src/main/java/view/ViewResolver.java
  src/main/java/webserver/WebServer.java
  src/main/resources/templates/index.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login_failed.html
Labels: step-6

#92 [감자] step5 쿠키,세션,어노테이션 미션구현
  README.md
  build.gradle
  src/main/java/Controller.java
  src/main/java/RequestMapping.java
  src/main/java/application/controller/Controller.java
  src/main/java/application/controller/DefaultController.java
  src/main/java/application/controller/DispatchServlet.java
  src/main/java/application/controller/FrontController.java
  src/main/java/application/controller/HomeController.java
  src/main/java/application/controller/LoginController.java
  src/main/java/application/controller/MyServlet.java
  src/main/java/application/controller/UserController.java
  src/main/java/application/controller/exception/HttpRequestException.java
  src/main/java/application/controller/exception/NotFindController.java
  src/main/java/application/db/Database.java
  src/main/java/application/model/User.java
  src/main/java/controller/Controller.java
  src/main/java/controller/DefaultController.java
  src/main/java/controller/FrontController.java
  src/main/java/controller/HomeController.java
  src/main/java/controller/UserController.java
  src/main/java/cookie/Cookie.java
  src/main/java/http/request/ContentType.java
  src/main/java/http/request/HttpRequest.java
  src/main/java/http/request/HttpRequestBody.java
  src/main/java/http/request/HttpRequestHeader.java
  src/main/java/http/request/HttpRequestStartLine.java
  src/main/java/http/response/HttpResponse.java
  src/main/java/http/response/HttpResponseHeader.java
  src/main/java/http/response/HttpStatus.java
  src/main/java/response/HttpResponse.java
  src/main/java/session/SessionManager.java
  src/main/java/util/HttpMethod.java
  src/main/java/view/Model.java
  src/main/java/view/ModelAndView.java
  src/main/java/view/MyView.java
  src/main/java/webserver/MappedRequest.java
  src/main/java/webserver/NotFoundException.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/RequestMapper.java
  src/main/java/webserver/RequestMapping.java
  src/main/java/webserver/WebServer.java
  src/main/java/webserver/annotation/Controller.java
  src/main/java/webserver/annotation/RequestMapping.java
  src/main/resources/templates/index.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/login.html
Labels: step-5

#94 1단계 index.html 응답 구현
  src/main/java/webserver/RequestHandler.java
  src/main/resources/static/index.html
Labels: step-1

#95 [poro] step-6 리팩토링, 템플릿 엔진 로직 개선, 세션,로깅 인터셉터 구현
  build.gradle
  src/main/java/controller/Controller.java
  src/main/java/controller/FrontController.java
  src/main/java/controller/HomeController.java
  src/main/java/interceptor/Interceptor.java
  src/main/java/mapper/HandlerMapper.java
  src/main/java/mapper/MappingInfoRepository.java
  src/main/java/mapper/MethodMap.java
  src/main/java/model/User.java
  src/main/java/response/ContentsType.java
  src/main/java/response/HttpResponse.java
  src/main/java/templateEngine/PoroTouch.java
  src/main/java/view/ModelAndView.java
  src/main/java/webserver/WebServer.java
  src/main/resources/templates/user/list.html
Labels: enhancement, step-6

#96 [cire] step-6 머스타치 템플릿 엔진 모방하여 구현 및 세션, 인터셉터 구현
  build.gradle
  src/main/java/configure/AppConfiguration.java
  src/main/java/configure/AppConfigure.java
  src/main/java/configure/ApplicationContext.java
  src/main/java/controller/DefaultController.java
  src/main/java/controller/UserController.java
  src/main/java/interceptor/DefaultInterceptor.java
  src/main/java/interceptor/Interceptor.java
  src/main/java/interceptor/LoginCheckInterceptor.java
  src/main/java/servlet/DispatcherServlet.java
  src/main/java/servlet/HttpRequest.java
  src/main/java/servlet/HttpResponse.java
  src/main/java/servlet/HttpServlet.java
  src/main/java/session/SessionManager.java
  src/main/java/type/ContentType.java
  src/main/java/util/HttpRequestParser.java
  src/main/java/util/Interpreter.java
  src/main/java/util/MethodAdaptor.java
  src/main/java/util/MyHandler.java
  src/main/java/util/MyLittleMustache.java
  src/main/java/util/RequestMapping.java
  src/main/java/view/ModelAndView.java
  src/main/java/view/MyView.java
  src/main/java/view/View.java
  src/main/java/view/ViewResolver.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
  src/main/resources/static/redirectFile.txt
  src/main/resources/templates/index.html
  src/main/resources/templates/user/list.html
  src/test/java/model/HeadParserTest.java
  src/test/java/model/HeadTest.java
  src/test/java/service/UserServiceTest.java
  src/test/java/util/MyLittleMustacheTest.java
Labels: step-6
